# Generated by Django 4.0.2 on 2022-02-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_name", models.CharField(max_length=255)),
                ("record_date", models.DateTimeField(verbose_name="date recorded")),
            ],
        ),
        migrations.CreateModel(
            name="Record_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_text", models.CharField(max_length=255)),
                ("priority", models.IntegerField(default=0)),
                (
                    "record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.record"
                    ),
                ),
            ],
        ),
    ]
