# Generated by Django 4.0.2 on 2022-02-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_data',
            name='data_text',
            field=models.TextField(max_length=255),
        ),
    ]
