# Generated by Django 4.0.2 on 2022-02-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_record_data_data_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date recorded'),
        ),
    ]
